server:
  port: 80

spring:
  application:
    name: cloud-provider-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#设置feign客户端超时时间(OpenFeign 默认支持ribbon)，如果不配置，超过5秒钟的请求会直接暴timeout异常
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
  ReadTimeout: 5000
  #指的是连接建立后,从服务器获取到可用资源所用时间
  ConnectTimeout: 5000

#feign 日志以什么级别监控那个接口
logging:
  level:
    com.henucg.service.PaymentService: debug