server:
  port: 9002

spring:
  application:
    name: cloudalibaba-provider-payment-service
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        # 通过Nginx注册到Nacos集群
        server-addr: 127.0.0.1:1111
